FROM node:22-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

# NEXT_PUBLIC_* values are baked in at build time, so each customer's branding
# is passed as build args (see docker-compose.private.yml).
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_DEPLOYMENT_MODE=private
ARG NEXT_PUBLIC_BRAND_NAME=FleetGuard
ARG NEXT_PUBLIC_BRAND_LOGO_URL=
ARG NEXT_PUBLIC_BRAND_ACCENT=
ARG NEXT_PUBLIC_BRAND_ACCENT_DARK=
ARG NEXT_PUBLIC_BRAND_ON_ACCENT=
ARG NEXT_PUBLIC_SITE_URL=http://localhost:3000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_DEPLOYMENT_MODE=$NEXT_PUBLIC_DEPLOYMENT_MODE \
    NEXT_PUBLIC_BRAND_NAME=$NEXT_PUBLIC_BRAND_NAME \
    NEXT_PUBLIC_BRAND_LOGO_URL=$NEXT_PUBLIC_BRAND_LOGO_URL \
    NEXT_PUBLIC_BRAND_ACCENT=$NEXT_PUBLIC_BRAND_ACCENT \
    NEXT_PUBLIC_BRAND_ACCENT_DARK=$NEXT_PUBLIC_BRAND_ACCENT_DARK \
    NEXT_PUBLIC_BRAND_ON_ACCENT=$NEXT_PUBLIC_BRAND_ON_ACCENT \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_TELEMETRY_DISABLED=1
RUN npm run build
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start"]
